import Head from "next/head";
import { Inter } from "next/font/google";
import Hero from "@/components/hero/hero";
import photos from "@/photos";
import { PhotoAlbum } from "react-photo-album";
import { Lightbox } from "yet-another-react-lightbox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section style={{ height: 500 }}>
          <Hero></Hero>
        </section>
        <section>
          <div className="container-xl border border-danger border-5 rounded p-0">
            <PhotoAlbum
              photos={photos}
              layout="columns"
              targetRowHeight={150}
              // onClick={({ index }) => setIndex(index)}
              spacing={5}
            />
          </div>
        </section>
      </main>
    </>
  );
}
